/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package itemApplication;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

import com.Item;
import com.Product;
public class Library {
     
	  EntityManager manager;
	  
         public Library() {
        	EntityManagerFactory emf = Persistence.createEntityManagerFactory("ProductPU");
     		manager = emf.createEntityManager();
         }
    public void saveProduct(Product product) {
    	
		manager.getTransaction().begin();
		manager.persist(product);
		manager.flush();
		manager.getTransaction().commit();
    }
    public Product findProduct(int id) {
    	Product pro= manager.find(Product.class, id);
    	return pro;
    }
    public boolean updateItem(Product product, int id) {
    	Product myproduct= findProduct(id);
    	myproduct.setProductName(product.getProductName());
    	myproduct.setPrice(product.getPrice());
    	manager.getTransaction().begin();
    	manager.merge(myproduct);
    	manager.flush();
    	manager.getTransaction().commit();
    	
    	return true;
    }
    public boolean remove(int id) {
    	Product p= findProduct(id);
    	manager.getTransaction().begin();
    	manager.remove(p);
    	manager.flush();
    	manager.getTransaction().commit();
    	return true;
    }
    
    public static void main(String[] args) {
		Product pro1 = new Product();
		pro1.setProductName("Shampoo");
		pro1.setPrice(250f);
		
		Product pro2 = new Product();
		pro2.setProductName("Hair Oil");
		pro2.setPrice(450f);
		Library lib = new Library();
		lib.saveProduct(pro1);
		lib.saveProduct(pro2);
		
		System.out.println(lib.findProduct(1).getProductName());
		System.out.println(lib.findProduct(2).getProductName());
		
		System.out.println(lib.updateItem(pro1, 1));
		System.out.println(lib.remove(2));
	}
}
